server:
  port: 8010
spring:
  application:
    name: consumer

eureka:
  client:
    service-url:
      defaultZone: http://kevin:kevin123@peer2:8762/eureka/,http://kevin:kevin123@peer1:8761/eureka/
    instance:
      prefer-ip-address: true
