server:
  port: 8040
spring:
  application:
    name: gateway-zuul

eureka:
  client:
    service-url:
      defaultZone: http://kevin:kevin123@peer2:8762/eureka/,http://kevin:kevin123@peer1:8761/eureka/
    instance:
      prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

