spring:
  application:
    name: eureka-server
  security:
    user:
      name: kevin
      password: kevin123
eureka:
  client:
    serviceUrl:
      defaultZone: http://kevin:kevin123@peer2:8762/eureka/,http://kevin:kevin123@peer1:8761/eureka/
---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2